name: Deploy SpeedBall Daemon

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Build Go binary
        run: |
          go mod tidy
          export CGO_ENABLED=0
          export GOOS=linux 
          export GOARCH=amd64
          go build -o speedball_api ./cmd/api && go build -o speedballd ./cmd/bot
          echo "Build completed."

      - name: Copy API binary to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "speedball_api, speedballd"
          target: "/etc/speedball"

      - name: Restart service on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo systemctl stop speedballd || true
            sudo systemctl stop speedball_api || true
            chmod +x /etc/speedball/speedball_api
            chmod +x /etc/speedball/speedballd
            sudo systemctl start speedballd
            sudo systemctl start speedball_api
